// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// col_normal_em_bb
List col_normal_em_bb(NumericVector ryo, NumericMatrix rxo, NumericMatrix rxaxa, NumericVector rd, NumericVector rlam, SEXP ralpha, SEXP rbeta, SEXP rselection);
RcppExport SEXP oda_col_normal_em_bb(SEXP ryoSEXP, SEXP rxoSEXP, SEXP rxaxaSEXP, SEXP rdSEXP, SEXP rlamSEXP, SEXP ralphaSEXP, SEXP rbetaSEXP, SEXP rselectionSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type ryo(ryoSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxo(rxoSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxaxa(rxaxaSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rd(rdSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rlam(rlamSEXP );
        Rcpp::traits::input_parameter< SEXP >::type ralpha(ralphaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rbeta(rbetaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rselection(rselectionSEXP );
        List __result = col_normal_em_bb(ryo, rxo, rxaxa, rd, rlam, ralpha, rbeta, rselection);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// col_normal_gibbs_bb
List col_normal_gibbs_bb(NumericVector ryo, NumericMatrix rxo, NumericMatrix rxa, NumericVector rlam, SEXP ralpha, SEXP rbeta, SEXP rburnin, SEXP rniter);
RcppExport SEXP oda_col_normal_gibbs_bb(SEXP ryoSEXP, SEXP rxoSEXP, SEXP rxaSEXP, SEXP rlamSEXP, SEXP ralphaSEXP, SEXP rbetaSEXP, SEXP rburninSEXP, SEXP rniterSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type ryo(ryoSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxo(rxoSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxa(rxaSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rlam(rlamSEXP );
        Rcpp::traits::input_parameter< SEXP >::type ralpha(ralphaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rbeta(rbetaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rburnin(rburninSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rniter(rniterSEXP );
        List __result = col_normal_gibbs_bb(ryo, rxo, rxa, rlam, ralpha, rbeta, rburnin, rniter);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// col_t_gibbs
List col_t_gibbs(NumericVector ryo, NumericMatrix rxo, NumericMatrix rxa, NumericVector rpriorprob, SEXP rburnin, SEXP rniter, SEXP ralpha);
RcppExport SEXP oda_col_t_gibbs(SEXP ryoSEXP, SEXP rxoSEXP, SEXP rxaSEXP, SEXP rpriorprobSEXP, SEXP rburninSEXP, SEXP rniterSEXP, SEXP ralphaSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type ryo(ryoSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxo(rxoSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxa(rxaSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rpriorprob(rpriorprobSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rburnin(rburninSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rniter(rniterSEXP );
        Rcpp::traits::input_parameter< SEXP >::type ralpha(ralphaSEXP );
        List __result = col_t_gibbs(ryo, rxo, rxa, rpriorprob, rburnin, rniter, ralpha);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// normal_em_bb
List normal_em_bb(NumericVector ryo, NumericMatrix rxo, NumericMatrix rxaxa, NumericVector rd, NumericVector rlam, SEXP ralpha, SEXP rbeta, SEXP rselection, SEXP rmaxiter);
RcppExport SEXP oda_normal_em_bb(SEXP ryoSEXP, SEXP rxoSEXP, SEXP rxaxaSEXP, SEXP rdSEXP, SEXP rlamSEXP, SEXP ralphaSEXP, SEXP rbetaSEXP, SEXP rselectionSEXP, SEXP rmaxiterSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type ryo(ryoSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxo(rxoSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxaxa(rxaxaSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rd(rdSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rlam(rlamSEXP );
        Rcpp::traits::input_parameter< SEXP >::type ralpha(ralphaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rbeta(rbetaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rselection(rselectionSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rmaxiter(rmaxiterSEXP );
        List __result = normal_em_bb(ryo, rxo, rxaxa, rd, rlam, ralpha, rbeta, rselection, rmaxiter);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// normal_em
List normal_em(NumericVector ryo, NumericMatrix rxo, NumericMatrix rxaxa, NumericVector rd, NumericVector rlam, NumericVector rpriorprob, SEXP rselection, SEXP rmaxiter);
RcppExport SEXP oda_normal_em(SEXP ryoSEXP, SEXP rxoSEXP, SEXP rxaxaSEXP, SEXP rdSEXP, SEXP rlamSEXP, SEXP rpriorprobSEXP, SEXP rselectionSEXP, SEXP rmaxiterSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type ryo(ryoSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxo(rxoSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxaxa(rxaxaSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rd(rdSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rlam(rlamSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rpriorprob(rpriorprobSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rselection(rselectionSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rmaxiter(rmaxiterSEXP );
        List __result = normal_em(ryo, rxo, rxaxa, rd, rlam, rpriorprob, rselection, rmaxiter);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// normal_gibbs
List normal_gibbs(NumericVector ryo, NumericMatrix rxo, NumericMatrix rxa, NumericVector rd, NumericVector rlam, NumericVector rpriorprob, SEXP rburnin, SEXP rniter);
RcppExport SEXP oda_normal_gibbs(SEXP ryoSEXP, SEXP rxoSEXP, SEXP rxaSEXP, SEXP rdSEXP, SEXP rlamSEXP, SEXP rpriorprobSEXP, SEXP rburninSEXP, SEXP rniterSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type ryo(ryoSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxo(rxoSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxa(rxaSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rd(rdSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rlam(rlamSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rpriorprob(rpriorprobSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rburnin(rburninSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rniter(rniterSEXP );
        List __result = normal_gibbs(ryo, rxo, rxa, rd, rlam, rpriorprob, rburnin, rniter);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// oda_gibbs
Rcpp::List oda_gibbs(Rcpp::NumericVector ryo, Rcpp::NumericMatrix rxo, Rcpp::NumericMatrix rxa, Rcpp::NumericMatrix rxoxo, Rcpp::NumericVector rd, Rcpp::NumericVector rlam, SEXP rmodelprior, Rcpp::NumericVector rpriorprob, SEXP rbeta1, SEXP rbeta2, SEXP rburnin, SEXP rniter, SEXP rscalemixture, SEXP ralpha, SEXP rcollapsed);
RcppExport SEXP oda_oda_gibbs(SEXP ryoSEXP, SEXP rxoSEXP, SEXP rxaSEXP, SEXP rxoxoSEXP, SEXP rdSEXP, SEXP rlamSEXP, SEXP rmodelpriorSEXP, SEXP rpriorprobSEXP, SEXP rbeta1SEXP, SEXP rbeta2SEXP, SEXP rburninSEXP, SEXP rniterSEXP, SEXP rscalemixtureSEXP, SEXP ralphaSEXP, SEXP rcollapsedSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ryo(ryoSEXP );
        Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type rxo(rxoSEXP );
        Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type rxa(rxaSEXP );
        Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type rxoxo(rxoxoSEXP );
        Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rd(rdSEXP );
        Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rlam(rlamSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rmodelprior(rmodelpriorSEXP );
        Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rpriorprob(rpriorprobSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rbeta1(rbeta1SEXP );
        Rcpp::traits::input_parameter< SEXP >::type rbeta2(rbeta2SEXP );
        Rcpp::traits::input_parameter< SEXP >::type rburnin(rburninSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rniter(rniterSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rscalemixture(rscalemixtureSEXP );
        Rcpp::traits::input_parameter< SEXP >::type ralpha(ralphaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rcollapsed(rcollapsedSEXP );
        Rcpp::List __result = oda_gibbs(ryo, rxo, rxa, rxoxo, rd, rlam, rmodelprior, rpriorprob, rbeta1, rbeta2, rburnin, rniter, rscalemixture, ralpha, rcollapsed);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// probit_normal_em
List probit_normal_em(NumericVector rbit, NumericMatrix rxo, NumericMatrix rxa, NumericVector rd, NumericVector rlam, NumericVector rpriorprob);
RcppExport SEXP oda_probit_normal_em(SEXP rbitSEXP, SEXP rxoSEXP, SEXP rxaSEXP, SEXP rdSEXP, SEXP rlamSEXP, SEXP rpriorprobSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type rbit(rbitSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxo(rxoSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxa(rxaSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rd(rdSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rlam(rlamSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rpriorprob(rpriorprobSEXP );
        List __result = probit_normal_em(rbit, rxo, rxa, rd, rlam, rpriorprob);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// probit_normal_gibbs
List probit_normal_gibbs(NumericVector rbit, NumericMatrix rxo, NumericMatrix rxa, NumericVector rd, NumericVector rlam, NumericVector rpriorprob, SEXP rburnin, SEXP rniter);
RcppExport SEXP oda_probit_normal_gibbs(SEXP rbitSEXP, SEXP rxoSEXP, SEXP rxaSEXP, SEXP rdSEXP, SEXP rlamSEXP, SEXP rpriorprobSEXP, SEXP rburninSEXP, SEXP rniterSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type rbit(rbitSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxo(rxoSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxa(rxaSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rd(rdSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rlam(rlamSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rpriorprob(rpriorprobSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rburnin(rburninSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rniter(rniterSEXP );
        List __result = probit_normal_gibbs(rbit, rxo, rxa, rd, rlam, rpriorprob, rburnin, rniter);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// t_em_bb
List t_em_bb(NumericVector ryo, NumericMatrix rxo, NumericMatrix rxaxa, NumericVector rd, SEXP ralpha, SEXP rbeta, SEXP rnu, SEXP rselection, SEXP rmaxiter);
RcppExport SEXP oda_t_em_bb(SEXP ryoSEXP, SEXP rxoSEXP, SEXP rxaxaSEXP, SEXP rdSEXP, SEXP ralphaSEXP, SEXP rbetaSEXP, SEXP rnuSEXP, SEXP rselectionSEXP, SEXP rmaxiterSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type ryo(ryoSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxo(rxoSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxaxa(rxaxaSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rd(rdSEXP );
        Rcpp::traits::input_parameter< SEXP >::type ralpha(ralphaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rbeta(rbetaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rnu(rnuSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rselection(rselectionSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rmaxiter(rmaxiterSEXP );
        List __result = t_em_bb(ryo, rxo, rxaxa, rd, ralpha, rbeta, rnu, rselection, rmaxiter);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// t_em
List t_em(NumericVector ryo, NumericMatrix rxo, NumericMatrix rxaxa, NumericVector rd, NumericVector rpriorprob, SEXP ralpha, SEXP rselection, SEXP rmaxiter);
RcppExport SEXP oda_t_em(SEXP ryoSEXP, SEXP rxoSEXP, SEXP rxaxaSEXP, SEXP rdSEXP, SEXP rpriorprobSEXP, SEXP ralphaSEXP, SEXP rselectionSEXP, SEXP rmaxiterSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type ryo(ryoSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxo(rxoSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxaxa(rxaxaSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rd(rdSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rpriorprob(rpriorprobSEXP );
        Rcpp::traits::input_parameter< SEXP >::type ralpha(ralphaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rselection(rselectionSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rmaxiter(rmaxiterSEXP );
        List __result = t_em(ryo, rxo, rxaxa, rd, rpriorprob, ralpha, rselection, rmaxiter);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// t_gibbs
List t_gibbs(NumericVector ryo, NumericMatrix rxo, NumericMatrix rxa, NumericVector rd, NumericVector rpriorprob, SEXP rburnin, SEXP rniter, SEXP ralpha);
RcppExport SEXP oda_t_gibbs(SEXP ryoSEXP, SEXP rxoSEXP, SEXP rxaSEXP, SEXP rdSEXP, SEXP rpriorprobSEXP, SEXP rburninSEXP, SEXP rniterSEXP, SEXP ralphaSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type ryo(ryoSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxo(rxoSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type rxa(rxaSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rd(rdSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rpriorprob(rpriorprobSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rburnin(rburninSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rniter(rniterSEXP );
        Rcpp::traits::input_parameter< SEXP >::type ralpha(ralphaSEXP );
        List __result = t_gibbs(ryo, rxo, rxa, rd, rpriorprob, rburnin, rniter, ralpha);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
